# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4714ad7cd87829cde90152e237c3653bbe8f99417141b4eaf451be5fc33f00993786cf4b92ffe2e840d6d83a3aab006eab206bf941daaed9992058d9c3233ce6

test:
  secret_key_base: 80fac31ee25144438415a7c0b38f38dff0909396daf960e418dfde92951ac4607fd3692f33fd08575b1dbfd2a5e44a2c18935a9a29947b73c887ec4bc2207939

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
